#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

#picom
pkill picom
picom -b &
#picom --expiremental-backends --no-use-damage &

# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

# panel
#tint2 &

source ~/.cache/wal/colors.sh

# set some bsp specific
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 6
bspc config border_width 4

bspc config active_border_color $background
bspc config normal_border_color $background
bspc config focused_border_color $foreground

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#rules
bspc rule -a discord desktop="^10"
bspc rule -a Spotify desktop="^9"
bspc rule -a Steam desktop="^8"
bspc rule -a firefox desktop="^2"

#other
setxkbmap us -variant colemak
setxkbmap -option "caps:backspace"
setxkbmap -option "shift:both_capslock"
~/.config/polybar/forest/scripts/pywal.sh ~/wallpapers/rick_and_morty_car_rainbow-wallpaper-1920x1080.jpg
~/.config/polybar/forest/scripts/styles.sh --dark
~/.config/polybar/launch.sh --forest
